[settings.pipx]
uvx = true

[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
azure-cli = "latest"
bat = "latest"
cargo-binstall = "latest"
"cargo:sheldon" = "latest"
checkov = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
gitleaks = "latest"
grype = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
"pipx:Faker" = "latest"
"pipx:coolname" = "latest"
"pipx:podman-compose" = "latest"
"pipx:tox" = "latest"
semgrep = "latest"
terraform = "latest"
uv = "latest"
yq = "latest"
zellij = "latest"
